[workspace]
resolver = "2"
members = [
    "rustformations",
    "transformations",
]
default-members = ["rustformations"]

[patch."https://github.com/envoyproxy/envoy"]
envoy-proxy-dynamic-modules-rust-sdk = { path = "patched-envoy-sdk/envoy-proxy-dynamic-modules-rust-sdk/dynamic_modules/sdk/rust" }
